# Generated by Django 5.1.2 on 2024-10-22 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_rut', models.CharField(blank=True, max_length=12, null=True)),
                ('specialist_rut', models.CharField(blank=True, max_length=12, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='horamedica_ficha_medica', to='usuarios.perfil')),
                ('specialist', models.ForeignKey(limit_choices_to={'user_type': 'specialist'}, on_delete=django.db.models.deletion.CASCADE, related_name='horamedica_specialist_medica', to='usuarios.perfil')),
            ],
        ),
    ]
