# Generated by Django 5.1.2 on 2024-10-25 01:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_medica', '0001_initial'),
        ('toma_de_hora', '0002_alter_horamedica_patient_alter_horamedica_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(help_text='Formato: +56912345678 o 912345678.', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe ser un número entre 7 y 15 dígitos.', regex='^\\+?[0-9]{7,15}$')])),
                ('correo_electronico', models.EmailField(help_text='Ingrese un correo electrónico válido.', max_length=254)),
                ('direccion', models.CharField(help_text='Ingrese la dirección completa.', max_length=255)),
                ('enfermedades_preexistentes', models.TextField(blank=True, help_text='Enumere las enfermedades preexistentes.')),
                ('alergias', models.TextField(blank=True, help_text='Enumere las alergias conocidas.')),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Enumere los medicamentos que está tomando actualmente.')),
                ('intervenciones_previas', models.TextField(blank=True, help_text='Enumere las intervenciones quirúrgicas previas.')),
                ('notas_especialista', models.TextField(blank=True, help_text='Notas del especialista sobre el paciente.')),
                ('hora_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='toma_de_hora.horamedica')),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
                'ordering': ['hora_medica'],
            },
        ),
        migrations.DeleteModel(
            name='HoraMedica',
        ),
    ]
