# Generated by Django 5.1.2 on 2024-10-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toma_de_hora', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horamedica',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='toma_hora_horamedica', to='usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='horamedica',
            name='specialist',
            field=models.ForeignKey(limit_choices_to={'user_type': 'specialist'}, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_horamedica', to='usuarios.perfil'),
        ),
    ]
